### DISCUSSION TITLE
Remote module interface validation error

### DISCUSSION THREAD

**Discussion by Klafyvel** [Ulm-IQO/qudi-core#127] [Q&A] [answered]
Hi, I am using a remote hardware module accessed from an interfuse. The remote module implements the `ProcessControlInterface`, and when the interfuse that connects to it is on the same machine everything works fine. However, when I try to use it on the remote I get the following error:
```
RuntimeError: Module "<qudi.hardware.laser.matisse.MatisseCommander(0x1ddd8cc1ef0) at 0x000001DDD9B328C0>" connected to connector "matisse" does not implement interface "ProcessControlInterface". It implements {'module', 'object'}. 
Traceback (most recent call last): 
 
  File "C:\Users\Molecola-II-Lab66\.conda\envs\qudi-env\lib\site-packages\qudi\core\modulemanager.py", line 201, in activate_module 
    self._modules[module_name].activate() 
 
  File "C:\Users\Molecola-II-Lab66\.conda\envs\qudi-env\lib\site-packages\qudi\core\modulemanager.py", line 505, in activate 
    self._connect() 
 
  File "C:\Users\Molecola-II-Lab66\.conda\envs\qudi-env\lib\site-packages\qudi\core\modulemanager.py", line 732, in _connect 
    self._instance.connect_modules(module_connections) 
 
  File "C:\Users\Molecola-II-Lab66\.conda\envs\qudi-env\lib\site-packages\qudi\core\module.py", line 408, in connect_modules 
    conn.connect(target) 
 
  File "C:\Users\Molecola-II-Lab66\.conda\envs\qudi-env\lib\site-packages\qudi\core\connector.py", line 90, in connect 
    raise RuntimeError(
 ```

For reference, here is the relevant configuration on the server, with a dummy example of how it works locally:
```
global: 
    # list of modules to load when starting 
    startup_modules: [] 
 
    # Module server configuration for accessing qudi GUI/logic/hardware modules from remote clients 
    remote_modules_server: 
        address: "an address" 
        port: a port 
    # Server port for serving the active qudi module namespace locally (localhost). 
    # Used by e.g. the Qudi jupyter kernel. 
    namespace_server_port: 18861 
 
    # If this flag is set (True), all arguments passed to qudi module APIs from remote 
    # (jupyter notebook, qudi console, remote modules) will be wrapped and passed "per value" 
    # (serialized and de-serialized). This is avoiding a lot of inconveniences with using numpy in 
    # remote clients. 
    # If you do not want to use this workaround and know what you are doing, you can disable this 
    # feature by setting this flag to False. 
    force_remote_calls_by_value: True 
 
    # Qss stylesheet for controlling the appearance of the GUIs. 
    # Absolute path or relative to qudi.artwork.styles 
    stylesheet: 'qdark.qss' 
 
    # Default root directory for measurement data storage. All eventual data sub-directories should 
    # be contained within this directory. This is not enforced, just convention. 
    # The fallback directory is <user home>/qudi/Data/ 
    default_data_dir: "C:/Users/NanoP/qudi/data" 
 
    # Save data to daily data sub-directories by default 
    daily_data_dirs: True 
gui:
    matisse_dummy: 
        module.Class: "excitation_scanner.excitation_gui.ScanningExcitationGui" 
        connect: 
            excitation_logic: matisse_excitation_logic 
logic: 
    matisse_excitation_logic: 
        module.Class: "scanning_excitation_spectroscopy.ScanningExcitationLogic" 
        connect: 
            scanner: matisse_scanner
hardware: 
    matisse_scanner: 
        module.Class: "interfuse.remote_matisse_scanner.RemoteMatisseScanner" 
        connect: 
            input: sampler_dummy 
            matisse: matisse_laser 
            matisse_sw: matisse_laser 
        options: 
            input_channel: "APD counts" 
    sampler_dummy: 
        module.Class: "dummy.finite_sampling_input_dummy.FiniteSamplingInputDummy" 
        options: 
            simulation_mode: LORENTZ 
    matisse_laser: 
        module.Class: "laser.matisse.MatisseCommander" 
        allow_remote: True 
        options: 
            address: "127.0.0.1" 
            port: 30000 
```

And here is the relevant configuration on the client:
```
global:
    # list of modules to load when starting
    startup_modules: []

    # Module server configuration for accessing qudi GUI/logic/hardware modules from remote clients
    remote_modules_server:
        address: 'localhost'
        port: 12345

    # Server port for serving the active qudi module namespace locally (localhost).
    # Used by e.g. the Qudi jupyter kernel.
    namespace_server_port: 18861

    # If this flag is set (True), all arguments passed to qudi module APIs from remote
    # (jupyter notebook, qudi console, remote modules) will be wrapped and passed "per value"
    # (serialized and de-serialized). This is avoiding a lot of inconveniences with using numpy in
    # remote clients.
    # If you do not want to use this workaround and know what you are doing, you can disable this
    # feature by setting this flag to False.
    force_remote_calls_by_value: True

    # Qss stylesheet for controlling the appearance of the GUIs.
    # Absolute path or relative to qudi.artwork.styles
    stylesheet: 'qdark.qss'

    # Default root directory for measurement data storage. All eventual data sub-directories should
    # be contained within this directory. This is not enforced, just convention.
    # The fallback directory is <user home>/qudi/Data/
    default_data_dir: "I:/Other computers/Spectro2021/Lab66_spectrometer_2021/DataLab37"

    # Save data to daily data sub-directories by default
    daily_data_dirs: True
gui:
    matisse_excitation_scanner:         
        module.Class: "excitation_scanner.excitation_gui.ScanningExcitationGui" 
            connect:
                excitation_logic: matisse_excitation_logic 
logic:
    matisse_excitation_logic:
        module.Class: "scanning_excitation_spectroscopy.ScanningExcitationLogic" 
        connect:
            scanner: matisse_scanner 
hardware:
    ni_finite_sampling_input:
        module.Class: 'ni_x_series.ni_x_series_finite_sampling_input.NIXSeriesFiniteSamplingInput'
        options:
            device_name: 'Dev1'
            digital_channel_units:  # optional
                pfi1: 'c/s'
                pfi2: 'c/s'
            # external_sample_clock_source: 'PFI0'  # optional
            # external_sample_clock_frequency: 1000  # optional
            adc_voltage_range: [-10, 10]  # optional, default [-10, 10]
            max_channel_samples_buffer: 10000000  # optional, default 10000000
            read_write_timeout: 10  # optional, default 10
            sample_clock_output: '/Dev1/PFI0'  # optiona
l            trigger_edge: RISING  # optional
    matisse_laser:
        native_module_name: "matisse_laser"
        address: "address of the server"
        port: port of te server 
    matisse_scanner:
         module.Class: "interfuse.remote_matisse_scanner.RemoteMatisseScanner" 
        connect:
            input: ni_finite_sampling_input 
            matisse: matisse_laser
            matisse_sw: matisse_laser 
        options:
            input_channel: "pfi1"
```
