### DISCUSSION TITLE
Upgrading Qudi from old version for confocal scanning

### DISCUSSION THREAD

**Discussion by d33psiloe** [Ulm-IQO/qudi-core#135] [Q&A] [answered]
Hi, I am trying to upgrade Qudi from older version for confocal scanning in hopes that it can reduce time for scanning
I am able to get it running; load hardware and launch confocal gui, but one thing that I noticed is that scanning results are vastly different from the results I have been getting using older Qudi. 

This one was the results with older qudi
![qudi_old](https://github.com/user-attachments/assets/8078ebd8-baec-4bf6-a03e-f260b24fc849)

and this is with new one

![qudi_new](https://github.com/user-attachments/assets/0bf58100-ea7e-4a40-a7e4-44a41300a0ed)

I scanned older one first and right after with new Qudi. Scan ranges and resolution are the same.

I'm new to this whole set up and I could really use some help.
Do you guys have any suggestions on why this is happening?

One thing, I have been getting this error when scanning. It was because there were NaN in `data` they were trying to convert in code.
Could this be related to my problem? 
![qudi_warning](https://github.com/user-attachments/assets/b3fc5622-3e01-4c98-a402-c709593f006e)

**Comment by timoML** [comment]
Hi, great that you're trying to upgrade your old installation!
Could you post the scanning hardware parts of your old and new config file?
It looks a bit like you're scanning in a different z layer, potentially because the voltage-to-distance configuration is different.

The warning message is most likely unrelated. Probably for the version of pyqtgraph in your environment, the NaN values is the scanning data for yet unscanned pixel lead to it. What version of pyqtgraph is this?

**Reply by d33psiloe** [reply]
Hi, thanks for the reply!

This is my old config file
```
hardware:
    nicard_6343:
        module.Class: 'national_instruments_x_series.NationalInstrumentsXSeries'
        photon_sources:
          - '/Dev1/PFI0'
            #  - '/Dev1/PFI8'
        clock_channel: '/Dev1/Ctr3'
        default_clock_frequency: 100 # optional, in Hz ##### frequency == rate means that 1/(Dwell time + Low time)   
        default_duty_cycle: 0.5      ##### duty_cycle == Dwell time / (Dwell time + Low time)      
        counter_channels:
            - '/Dev1/Ctr2'
        counter_ai_channels:
            - '/Dev1/AI0'
        counter_voltage_range: [-10, 10]
        default_scanner_clock_frequency: 100 # optional, in Hz
        scanner_clock_channel: '/Dev1/Ctr3'
        pixel_clock_channel: '/Dev1/PFI6'
        scanner_ao_channels:
            - '/Dev1/AO0'
            - '/Dev1/AO1'
            - '/Dev1/AO2'
            - '/Dev1/AO3'
        scanner_ai_channels:
            - '/Dev1/AI29'
        scanner_counter_channels:
            - '/Dev1/Ctr0'
            # - '/Dev1/Ctr2'
        scanner_voltage_ranges:
            - [-10, 10]
            - [-10, 10]
            - [-10, 10]
            - [-10, 10]
        scanner_position_ranges:
            - [0e-6, 200e-6]
            - [0e-6, 200e-6]
            - [0, 20e-6]
            - [-10, 10]
            #- [0e-6, 100e-6]
            #- [0e-6, 100e-6]
            #- [0e-6, 100e-6]
            #- [-10, 10]

        odmr_trigger_channel: '/Dev1/PFI7'
        gate_in_channel: '/Dev1/PFI9'
        default_samples_number: 50
        max_counts: 3e7
        read_write_timeout: 10
        counting_edge_rising: True

    nicard_6343_instreamer:
        module.Class: 'ni_x_series_in_streamer.NIXSeriesInStreamer'
        device_name: 'Dev1'
        digital_sources:  # optional
            - 'PFI0'
            - 'PFI8'
        analog_sources:  # optional
            - 'ai0'
            - 'ai1'
        # external_sample_clock_source: 'PFI0'  # optional
        # external_sample_clock_frequency: 1000  # optional
        adc_voltage_range: [-10, 10]  # optional
        max_channel_samples_buffer: 10000000  # optional
        read_write_timeout: 10  # optional
```

and my new one

```
hardware:
    nicard_6353_scanner:
        module.Class: 'interfuse.ni_scanning_probe_interfuse.NiScanningProbeInterfuse'
        connect:
            scan_hardware: 'ni_io'
            analog_output: 'ni_ao'
        options:  
            ni_channel_mapping:
                x: 'ao0'
                y: 'ao1'
                z: 'ao2'
                fluorescence: 'PFI8'
            position_ranges: # in m
                x: [0, 200e-6]
                y: [0, 200e-6]
                z: [0, 200e-6]
            frequency_ranges:
                x: [1, 500]
                y: [1, 500]
                z: [1, 500]
            resolution_ranges:
                x: [1, 1000]
                y: [1, 1000]
                z: [1, 1000]
            input_channel_units:
                fluorescence: 'c/s'
            backwards_line_resolution: 10 # optional
            maximum_move_velocity: 400e-6 #m/s

    ni_io:
        module.Class: 'ni_x_series.ni_x_series_finite_sampling_io.NIXSeriesFiniteSamplingIO'
        options:
            device_name: 'Dev1'
            input_channel_units:  # optional
                PFI8: 'c/s'
                #PFI9: 'c/s'
                #PFI10: 'c/s'
                #ai0: 'V'
                #ai1: 'V'
            output_channel_units:
                'ao0': 'V'
                'ao1': 'V'
                'ao2': 'V'
            adc_voltage_ranges:
                #ai0: [-10, 10]  # optional
                #ai1: [-10, 10]  # optional
            output_voltage_ranges:
                ao0: [-10, 10]
                ao1: [-10, 10]
                ao2: [-10, 10]

            frame_size_limits: [1, 1e9]  # optional #TODO actual HW constraint?
            output_mode: 'JUMP_LIST' #'JUMP_LIST' # optional, must be name of SamplingOutputMode
            read_write_timeout: 10  # optional
            #sample_clock_output: '/Dev1/PFI11' # optional

    ni_ao:
        module.Class: 'ni_x_series.ni_x_series_analog_output.NIXSeriesAnalogOutput'
        options:
            device_name: 'Dev1'
            channels:
                ao0:
                    limits: [-10.0, 10.0]
                    keep_value: True
                ao1:
                    limits: [-10.0, 10.0]
                    keep_value: True
                ao2:
                    limits: [-10.0, 10.0]
                    keep_value: True

    nicard_6353_instreamer:
        module.Class: 'ni_x_series.ni_x_series_in_streamer.NIXSeriesInStreamer'
        options:
            device_name: 'Dev1'
            digital_sources:  # optional
                - 'PFI0'
                - 'PFI8'
            analog_sources:  # optional
                - 'ai0'
                - 'ai1'
            # external_sample_clock_source: 'PFI0'  # optional
            # external_sample_clock_frequency: 1000  # optional
            adc_voltage_range: [-10, 10]  # optional
            max_channel_samples_buffer: 10000000  # optional
            read_write_timeout: 10  # optional
```
I just copied the [docs](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/docs/setup_confocal_scanning.md) 

and for the warning msgs I'm using pygtgraph 0.13.3
