### DISCUSSION TITLE
Working remote with a Qudi server

### DISCUSSION THREAD

**Discussion by fhaltenberger** [Ulm-IQO/qudi-core#150] [Q&A]
Hey guys, 

I'm kind of new to Qudi and my goal is to set up a remote access framework so that people can use our experimental setup that is controlled by Qudi from their own laptops in our group.
The way I imagine doing this is by connecting to the RemoteModulesServer, with which I can for example use the methods from e.g. the PulsedMasterLogic programatically to, lets say, define a pulse sequence, execute it and get the photon counts back.
Is this the intended use of the RemoteModulesServer (I'll call it RMS from here on)? 
If so, then I have a problem, because I cant connect to the RMS via rpyc the same way I can connect to the QudiNamespaceServer locally. I defined two different ports for the QudiNamespaceServer (QNS) (port 18861) and the RMS (port 12345) in my cfg-file, defined the shared modules (only including the PulsedMasterLogic (PML) for now), and set allow_remote: True for the PML. 
Now, on the machine that is running qudi, I can access the QNS via conn = rpyc.connect("localhost", 18861), and then access the different modules from qudi's namespace via conn.root. Here I then also do RMS.share_module(pulsed_master_logic), which then also appears in the RemoteModuleService's get_shared_module_names() function.
But when I try to connect to the RMS (locally), via conn = rpyc.connect("localhost", 12345, config={"allow_setattr": True,...}), the connection is successful, but when I call conn.root, it says "EOFError: connection reset by peer". 
I thought it may be due to SSL stuff, so I also tried it with a .key and .crt file, but that also didn't work (also qudi suggests that it isn't necessary anyway).
I also thought it may be due to the threaded nature of the server, but when I list the threads, I see one for the RMS. I didn not dive much deeper into that yet.
I also make sure (via rpyc access on the QNS), that the RMS server is running. Also the log file doesn't give me any hint as to why the server shuts down immediately. 
I also tried changing the address of the RMS in the cfg-file from "localhost" to "0.0.0.0" but that also didn't work. Again, all of the above is only for the local case, where I try to access the RMS from within the same machine. I also tried accessing it from a different container (thinking that maybe the RMS ONLY allows remote access) but that also did not work and shows the same problems.

Any help on this would be greatly appreciated! I have tried to solve it for the last two days straight...

Kindly, Fritz

**Comment by fhaltenberger** [comment]
In other config exampes I see that only hardware modules are configed to have allow_remote: True. Are logic modules not intended to be accessed remotely? And if so, if I want to for example define a Rabi oscillation experiment on a remote laptop which should be executed on my server running qudi, should i have my own logic modules on my local PC that connect to the remote hardware? Or should I write a script on my local laptop which is sent to the qudi server, which then internally interacts with the QudiNamespaceKernel?

**Reply by TobiasSpohn** [reply]
Hi @fhaltenberger,

Personally, I have never tried running a logic module remotely, although I think it should be possible generally. The only thing one needs to watch out for is that if any more complex objects (e.g. numpy arrays or so) rpyc does not always send all the necessary information, which might cause errors in other logic or GUI modules. Sometimes an explicit netobtain() call is then required on the receiving end.

However, your problem seems to be with already setting up the connection. I tested remote connections on my local machine with just running 2 instances of qudi on different configurations.
<details><summary>client.cfg</summary>
<p>

```
#  Example Qudi configuration file.
#  The recommended path for user specific files is C:\Users\<user_name>\qudi\config

global:
    # list of modules to load when starting
    startup_modules: []

    # Module server configuration for accessing qudi GUI/logic/hardware modules from remote clients
    #remote_modules_server:
    #    address: 'localhost'
    #    port: 12345

    # Server port for serving the active qudi module namespace locally (localhost).
    # Used by e.g. the Qudi jupyter kernel.
    namespace_server_port: 18862

    # If this flag is set (True), all arguments passed to qudi module APIs from remote
    # (jupyter notebook, qudi console, remote modules) will be wrapped and passed "per value"
    # (serialized and de-serialized). This is avoiding a lot of inconveniences with using numpy in
    # remote clients.
    # If you do not want to use this workaround and know what you are doing, you can disable this
    # feature by setting this flag to False.
    force_remote_calls_by_value: True

    # Qss stylesheet for controlling the appearance of the GUIs.
    # Absolute path or relative to qudi.artwork.styles
    stylesheet: 'qdark.qss'

    # Default root directory for measurement data storage. All eventual data sub-directories should
    # be contained within this directory. This is not enforced, just convention.
    # The fallback directory is <user home>/qudi/Data/
    # default_data_dir: C:\Users\neverhorst\qudi\Data

    # Save data to daily data sub-directories by default
    daily_data_dirs: True

gui:
    pulsed_gui:
        module.Class: 'pulsed.pulsed_maingui.PulsedMeasurementGui'
        connect:
            pulsedmasterlogic: 'pulsed_master_logic'

logic:
    pulsed_master_logic:
        module.Class: 'pulsed.pulsed_master_logic.PulsedMasterLogic'
        connect:
            pulsedmeasurementlogic: 'pulsed_measurement_logic'
            sequencegeneratorlogic: 'sequence_generator_logic'

    sequence_generator_logic:
        module.Class: 'pulsed.sequence_generator_logic.SequenceGeneratorLogic'
        #overhead_bytes: 0
        #additional_predefined_methods_path: null
        #additional_sampling_functions_path: null
        #assets_storage_path:
        connect:
            pulsegenerator: 'pulser_dummy'

    pulsed_measurement_logic:
        module.Class: 'pulsed.pulsed_measurement_logic.PulsedMeasurementLogic'
        options:
            raw_data_save_type: 'text'
            #additional_extraction_path:
            #additional_analysis_path:
        connect:
            fastcounter: 'fast_counter_dummy'
            #microwave: 'microwave_dummy'
            pulsegenerator: 'pulser_dummy'

hardware:
    fast_counter_dummy:
        module.Class: 'dummy.fast_counter_dummy.FastCounterDummy'
        options:
            gated: False

    pulser_dummy:
        native_module_name: "pulser_dummy"
        address: 'localhost'
        port: 12345
```


</p>
</details> 

<details><summary>server.cfg</summary>
<p>

```
#  Example Qudi configuration file.
#  The recommended path for user specific files is C:\Users\<user_name>\qudi\config

global:
    # list of modules to load when starting
    startup_modules: []

    # Module server configuration for accessing qudi GUI/logic/hardware modules from remote clients
    remote_modules_server:
        address: 'localhost'
        port: 12345

    # Server port for serving the active qudi module namespace locally (localhost).
    # Used by e.g. the Qudi jupyter kernel.
    namespace_server_port: 18861

    # If this flag is set (True), all arguments passed to qudi module APIs from remote
    # (jupyter notebook, qudi console, remote modules) will be wrapped and passed "per value"
    # (serialized and de-serialized). This is avoiding a lot of inconveniences with using numpy in
    # remote clients.
    # If you do not want to use this workaround and know what you are doing, you can disable this
    # feature by setting this flag to False.
    force_remote_calls_by_value: True

    # Qss stylesheet for controlling the appearance of the GUIs.
    # Absolute path or relative to qudi.artwork.styles
    stylesheet: 'qdark.qss'

    # Default root directory for measurement data storage. All eventual data sub-directories should
    # be contained within this directory. This is not enforced, just convention.
    # The fallback directory is <user home>/qudi/Data/
    # default_data_dir: C:\Users\neverhorst\qudi\Data

    # Save data to daily data sub-directories by default
    daily_data_dirs: True

logic:
    pulsed_master_logic:
        module.Class: 'pulsed.pulsed_master_logic.PulsedMasterLogic'
        connect:
            pulsedmeasurementlogic: 'pulsed_measurement_logic'
            sequencegeneratorlogic: 'sequence_generator_logic'

    sequence_generator_logic:
        module.Class: 'pulsed.sequence_generator_logic.SequenceGeneratorLogic'
        #overhead_bytes: 0
        #additional_predefined_methods_path: null
        #additional_sampling_functions_path: null
        #assets_storage_path:
        connect:
            pulsegenerator: 'pulser_dummy'

    pulsed_measurement_logic:
        module.Class: 'pulsed.pulsed_measurement_logic.PulsedMeasurementLogic'
        options:
            raw_data_save_type: 'text'
            #additional_extraction_path:
            #additional_analysis_path:
        connect:
            fastcounter: 'fast_counter_dummy'
            #microwave: 'microwave_dummy'
            pulsegenerator: 'pulser_dummy'

hardware:
    fast_counter_dummy:
        module.Class: 'dummy.fast_counter_dummy.FastCounterDummy'
        options:
            gated: False

    pulser_dummy:
        module.Class: 'dummy.pulser_dummy.PulserDummy'
        allow_remote: True
        options:
            force_sequence_option: False
```


</p>
</details> 

Then I just activated the ``pulser_dummy`` in the server instance and subsequently activated ``pulsed_gui`` in the client session. This worked, I can load the toolchain and upload sequences.

For your case, where the whole logic toolchain is on the server and only the gui on the client I used this:

<details><summary>client.cfg</summary>
<p>

```
#  Example Qudi configuration file.
#  The recommended path for user specific files is C:\Users\<user_name>\qudi\config

global:
    # list of modules to load when starting
    startup_modules: []

    # Module server configuration for accessing qudi GUI/logic/hardware modules from remote clients
    #remote_modules_server:
    #    address: 'localhost'
    #    port: 12345

    # Server port for serving the active qudi module namespace locally (localhost).
    # Used by e.g. the Qudi jupyter kernel.
    namespace_server_port: 18862

    # If this flag is set (True), all arguments passed to qudi module APIs from remote
    # (jupyter notebook, qudi console, remote modules) will be wrapped and passed "per value"
    # (serialized and de-serialized). This is avoiding a lot of inconveniences with using numpy in
    # remote clients.
    # If you do not want to use this workaround and know what you are doing, you can disable this
    # feature by setting this flag to False.
    force_remote_calls_by_value: True

    # Qss stylesheet for controlling the appearance of the GUIs.
    # Absolute path or relative to qudi.artwork.styles
    stylesheet: 'qdark.qss'

    # Default root directory for measurement data storage. All eventual data sub-directories should
    # be contained within this directory. This is not enforced, just convention.
    # The fallback directory is <user home>/qudi/Data/
    # default_data_dir: C:\Users\neverhorst\qudi\Data

    # Save data to daily data sub-directories by default
    daily_data_dirs: True

gui:
    pulsed_gui:
        module.Class: 'pulsed.pulsed_maingui.PulsedMeasurementGui'
        connect:
            pulsedmasterlogic: 'pulsed_master_logic'

logic:
    pulsed_master_logic:
        native_module_name: "pulsed_master_logic"
        address: 'localhost'
        port: 12345

```


</p>
</details> 

<details><summary>server.cfg</summary>
<p>

```
#  Example Qudi configuration file.
#  The recommended path for user specific files is C:\Users\<user_name>\qudi\config

global:
    # list of modules to load when starting
    startup_modules: []

    # Module server configuration for accessing qudi GUI/logic/hardware modules from remote clients
    remote_modules_server:
        address: 'localhost'
        port: 12345

    # Server port for serving the active qudi module namespace locally (localhost).
    # Used by e.g. the Qudi jupyter kernel.
    namespace_server_port: 18861

    # If this flag is set (True), all arguments passed to qudi module APIs from remote
    # (jupyter notebook, qudi console, remote modules) will be wrapped and passed "per value"
    # (serialized and de-serialized). This is avoiding a lot of inconveniences with using numpy in
    # remote clients.
    # If you do not want to use this workaround and know what you are doing, you can disable this
    # feature by setting this flag to False.
    force_remote_calls_by_value: True

    # Qss stylesheet for controlling the appearance of the GUIs.
    # Absolute path or relative to qudi.artwork.styles
    stylesheet: 'qdark.qss'

    # Default root directory for measurement data storage. All eventual data sub-directories should
    # be contained within this directory. This is not enforced, just convention.
    # The fallback directory is <user home>/qudi/Data/
    # default_data_dir: C:\Users\neverhorst\qudi\Data

    # Save data to daily data sub-directories by default
    daily_data_dirs: True

logic:
    pulsed_master_logic:
        module.Class: 'pulsed.pulsed_master_logic.PulsedMasterLogic'
        allow_remote: True
        connect:
            pulsedmeasurementlogic: 'pulsed_measurement_logic'
            sequencegeneratorlogic: 'sequence_generator_logic'

    sequence_generator_logic:
        module.Class: 'pulsed.sequence_generator_logic.SequenceGeneratorLogic'
        #overhead_bytes: 0
        #additional_predefined_methods_path: null
        #additional_sampling_functions_path: null
        #assets_storage_path:
        connect:
            pulsegenerator: 'pulser_dummy'

    pulsed_measurement_logic:
        module.Class: 'pulsed.pulsed_measurement_logic.PulsedMeasurementLogic'
        options:
            raw_data_save_type: 'text'
            #additional_extraction_path:
            #additional_analysis_path:
        connect:
            fastcounter: 'fast_counter_dummy'
            #microwave: 'microwave_dummy'
            pulsegenerator: 'pulser_dummy'

hardware:
    fast_counter_dummy:
        module.Class: 'dummy.fast_counter_dummy.FastCounterDummy'
        options:
            gated: False

    pulser_dummy:
        module.Class: 'dummy.pulser_dummy.PulserDummy'
        options:
            force_sequence_option: False

```


</p>
</details> 

This worked partly: I can load ``pulsed_master_logic`` on the client side and make calls to it, e.g. ``pulsed_master_logic.pulse_generator_constraints.waveform_length``. 
Also the server shows an information in its log: ``Client connected to remote modules service from [127.0.0.1]:43464``
However, when I try to load the GUI I get an error: 
```
 Exception during activation:

ValueError: 'PySide2.QtWidgets.QAbstractItemView.setModel' called with wrong argument values:
  PySide2.QtWidgets.QAbstractItemView.setModel(<qudi.util.datafitting.FitConfigurationsModel(0x7f05180173a0) at 0x7f055c174980>,)
Found signature:
  PySide2.QtWidgets.QAbstractItemView.setModel(PySide2.QtCore.QAbstractItemModel)
Traceback (most recent call last):

  File "/home/tobi/qudi/qudi-core/src/qudi/core/module.py", line 309, in __activation_callback
    self.on_activate()

  File "/home/tobi/qudi/qudi-iqo-modules/src/qudi/gui/pulsed/pulsed_maingui.py", line 192, in on_activate
    self._fcd = FitConfigurationDialog(

  File "/home/tobi/qudi/qudi-core/src/qudi/util/widgets/fitting.py", line 178, in __init__
    self.fit_config_widget = FitConfigurationWidget(fit_config_model=fit_config_model)

  File "/home/tobi/qudi/qudi-core/src/qudi/util/widgets/fitting.py", line 149, in __init__
    self.config_listview.setModel(fit_config_model)
 
```

I currently don't have the time to dig deeper into this, but it seems to me that it might originate from the problem I stated at the beginning. A higher object (FitConfigurationsModel) is passed through the remote connection and something fails there. However, I can't reproduce your problem. Technically, having a remote logic should work. Did you check that you set the correct firewall settings?
