### DISCUSSION TITLE
Programming Guidelines - adding new hw

### DISCUSSION THREAD

**Discussion by AItah** [Ulm-IQO/qudi-core#81] [Q&A] [answered]
Hi,

I would like to add Swabian pulse streamer 8/2 to qudi as a reference to understand how to add real HW device and how to add HW device.
Starting by commenting:
;    instream_dummy:
;        module.Class: 'dummy.data_instream_dummy.InStreamDummy'
;        options:
;            channel_names:
;                - 'digital 1'
;                - 'analog 1'
;                - 'analog 2'
;                - 'digital 2'
;            channel_units:
;                - 'Hz'
;                - 'V'
;                - 'V'
;                - 'Hz'
;            channel_signals:  # Can be 'counts' or 'sine'
;                - 'counts'
;                - 'sine'
;                - 'sine'
;                - 'counts'
;            data_type: 'float64'
;            sample_timing: 'CONSTANT'  # Can be 'CONSTANT', 'TIMESTAMP' or 'RANDOM'

later adding:
pulsestreamer:
        module.Class: 'swabian_instruments.pulse_streamer.PulseStreamer'
        options:
            pulsestreamer_ip: '192.168.1.100'
            #pulsed_file_dir: 'C:\\Software\\pulsed_files'
            laser_channel: 0
            uw_x_channel: 1
            use_external_clock: False
            external_clock_option: 0

results with no module that is loaded.

Can you please guide where to find more info about how to add HW instead of dummy one and how to change correctly the cfg file to use HW that is already supported by qudi?

BTW the programming guidelines link is broken (https://github.com/Ulm-IQO/qudi-core/blob/main/docs/programming_guidelin) maybe 'es' is missing?

BR,
Amir

**Comment by AItah** [comment]
Also noticed that for an HW there are: Gui, Interface, HW, and logic. (for example: cameragui.py, camera_interface.py, camera_logic.py, camera_dummy.py).
I guess that gui is gui, interface to make the SW kind of common and generic regardless with the attached device model, HW (dummy) is probably a wrapper for a specific device, however, I am not sure about logic. Can you please explain what is logic?

**Comment by timoML** [comment]
When researching the documentation, please start [here](https://ulm-iqo.github.io/qudi-core/). Links in there should refer to up-to-date documentation files. I think both your questions should be addressed in the "Configuration" and "Qudi Measurement Modules" sections.
We're trying our best to fill the gaps (topics without links), but this may take a while.

Additionally, there are some example configs in the [iqo-modules docs](https://github.com/Ulm-IQO/qudi-iqo-modules/blob/main/docs/installation_guide.md#qudi-configuration).

Concerning your example config: Can you describe in more detail what the issue is? Are you getting any errors in the manager?

**Comment by AItah** [comment]
Dear Timo,

I am adding:
 ```
   pulsestreamer:
        module.Class: 'swabian_instruments.pulse_streamer.PulseStreamer'
        options:
            pulsestreamer_ip: '192.168.1.100'
            #pulsed_file_dir: 'C:\\Software\\pulsed_files'
            laser_channel: 0
            uw_x_channel: 1
            use_external_clock: False
            external_clock_option: 0
```


into default.cfg (located under my c:\users\user name\qudi\config folder).

However, cannot see the pulse streamer.

I guess it is ok since I did not set any GUI configuration.

So, I guess the issues is that I am not sure how to set Pulse streamer correctly in the CFG file.
