### ISSUE TITLE
[Bug] Schema validation fails for remote modules

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi-core#27]
### Version

current main

### What is affected by the bug?

This part of the schema validation fails because properties for local modules get injected into the config that is being validated:
```
'additionalProperties': {
                    'oneOf': [
                        {'$ref': '#/$defs/local_module'},
                        {'$ref': '#/$defs/remote_module'}
                    ]

```

### When does the bug occur?

While loading a config with remote modules.

### How do we replicate the issue?

Load this config (NVision internal modules needed) or write an equivalent one yourself.
```
#  Example Qudi configuration file.
#

global:
    # list of modules to load when starting
    startup: []

    remote_modules_server:
        address: 'localhost'
        port: 12345

    namespace_server_port: 18861

    #default_data_dir: 'C:\\Data'

    ## For controlling the appearance of the GUI:
    #stylesheet: 'C:\\Software\\qudi\\qudi-nvision-modules\\src\\qudi\\artwork\\styles\\application\\nvision_laser_v01.qss' # 'qdark.qss'

logic:
    commandlogic:
        module.Class: 'nmr_command_logic.NMRCommandLogic'
        connect:
            command_receiver: 'fieldcyclinglogic'
        options:
            input_pipe: '/home/nmrsu/qudi/qudipipe'
            output_pipe: '/home/nmrsu/qudi/nmrpipe'
            query_interval: 0.1
            
    fieldcyclinglogic:
        native_module_name: 'field_cycling_logic'
        address: '192.168.1.207'
        port: 12345

```

### Expected behavior

Qudi should accept this config as valid and be usable.

### Relevant log output

```shell
--
```

### Additional Comments

Current workaround is to set  `'additionalProperties': True,`  in `remote_module_config_schema()`.
