### ISSUE TITLE
[Bug] Remote module connection fails with timeout without adequate error messages or documentation

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi-core#28]
### Version

current main

### What is affected by the bug?

Activating a remote module in Qudi fails with a rather obscure SSL timeout error.

### When does the bug occur?

When no `certfile` and `keyfile` is passed to `get_remote_module_instance(...)`, `rpyc.ssl_connect(...)` simply produces a timeout.

### How do we replicate the issue?

Use a config like the one below (NVision internal modules required for this exact example), and a config exporting the remote modules used here with `allow_remote: True`  on the module server.

When activating `fieldcyclinglogic` , the remote connection will fail with an `SSLTimeout` while trying to negotiate an encrypted connection despite the fact that no certificates for encryption have been specified.

```
#  Example Qudi configuration file.
#

global:
    # list of modules to load when starting
    startup: []

    remote_modules_server:
        address: 'localhost'
        port: 12345

    namespace_server_port: 18861

    #default_data_dir: 'C:\\Data'

    ## For controlling the appearance of the GUI:
    #stylesheet: 'C:\\Software\\qudi\\qudi-nvision-modules\\src\\qudi\\artwork\\styles\\application\\nvision_laser_v01.qss' # 'qdark.qss'

logic:
    commandlogic:
        module.Class: 'nmr_command_logic.NMRCommandLogic'
        connect:
            command_receiver: 'fieldcyclinglogic'
        options:
            input_pipe: '/home/nmrsu/qudi/qudipipe'
            output_pipe: '/home/nmrsu/qudi/nmrpipe'
            query_interval: 0.1
            
    fieldcyclinglogic:
        native_module_name: 'field_cycling_logic'
        address: '192.168.1.207'
        port: 12345
```

### Expected behavior

Either a proper error message about connection encryption and documentation for setting up connection encryption or unencrypted `rpyc` connections when no `certfile` and `keyfile` are specified.

### Additional Comments

Current workaround is this patch:
```
diff --git a/src/qudi/core/servers.py b/src/qudi/core/servers.py
index 94e9d5d3..01a043a6 100644
--- a/src/qudi/core/servers.py
+++ b/src/qudi/core/servers.py
@@ -52,11 +52,11 @@ def get_remote_module_instance(remote_url, certfile=None, keyfile=None, protocol
                            'allow_delattr': True,
                            'allow_pickle': True,
                            'sync_request_timeout': 3600}
-    connection = rpyc.ssl_connect(host=parsed.hostname,
+    connection = rpyc.connect(host=parsed.hostname,
                                   port=parsed.port,
-                                  config=protocol_config,
-                                  certfile=certfile,
-                                  keyfile=keyfile)
+                                  config=protocol_config)
+                                  #certfile=certfile,
+                                  #keyfile=keyfile)
     logger.debug(f'get_remote_module_instance has protocol_config {protocol_config}')
     return connection.root.get_module_instance(parsed.path.replace('/', ''))
```
